### ISSUE TITLE
Getting Realdebrid cache error when only Torbox is enabled.

### ISSUE THREAD

**Issue by subexx** [rivenmedia/riven#408]
I only have torbox enabled. But getting error related to realdebrid.

```
2024-06-15 13:19:20 | ✨ NEW       | program._submit_job - Submitting service TraktIndexer to the pool with The Fall Guy
2024-06-15 13:19:20 | 🤖 PROGRAM   | program._submit_job - Submitting service Scraping to the pool with The Fall Guy
2024-06-15 13:19:22 | 👻 SCRAPER   | torbox.scrape - Found 35 streams out of 107 for The Fall Guy
2024-06-15 13:19:22 | 🤖 PROGRAM   | program._submit_job - Submitting service Debrid to the pool with The Fall Guy
2024-06-15 13:19:22 | 🔗 DEBRID    | realdebrid.is_cached - Processing 35 streams for The Fall Guy
2024-06-15 13:19:22 | ❌ ERROR     | realdebrid.is_cached - Error checking cache for streams
Traceback (most recent call last):
  File "/iceberg/backend/program/downloaders/realdebrid.py", line 123, in is_cached
    response = get(f"{RD_BASE_URL}/torrents/instantAvailability/{streams}/", additional_headers=self.auth_headers, response_type=dict)
  File "/iceberg/backend/utils/request.py", line 119, in get
    return _make_request(
  File "/iceberg/backend/utils/request.py", line 102, in _make_request
    return ResponseObject(response, response_type)
  File "/iceberg/backend/utils/request.py", line 33, in __init__
    self.data = self.handle_response(response)
  File "/iceberg/backend/utils/request.py", line 44, in handle_response
    raise RequestException(f"Client error with status {self.status_code}", response=response)
requests.exceptions.RequestException: Client error with status 401
2024-06-15 13:19:23 | ❌ ERROR     | realdebrid.is_cached - Error checking cache for streams
Traceback (most recent call last):
  File "/iceberg/backend/program/downloaders/realdebrid.py", line 123, in is_cached
    response = get(f"{RD_BASE_URL}/torrents/instantAvailability/{streams}/", additional_headers=self.auth_headers, response_type=dict)
  File "/iceberg/backend/utils/request.py", line 119, in get
    return _make_request(
  File "/iceberg/backend/utils/request.py", line 102, in _make_request
    return ResponseObject(response, response_type)
  File "/iceberg/backend/utils/request.py", line 33, in __init__
    self.data = self.handle_response(response)
  File "/iceberg/backend/utils/request.py", line 44, in handle_response
    raise RequestException(f"Client error with status {self.status_code}", response=response)
requests.exceptions.RequestException: Client error with status 401
2024-06-15 13:19:24 | ❌ ERROR     | realdebrid.is_cached - Error checking cache for streams
Traceback (most recent call last):
  File "/iceberg/backend/program/downloaders/realdebrid.py", line 123, in is_cached
    response = get(f"{RD_BASE_URL}/torrents/instantAvailability/{streams}/", additional_headers=self.auth_headers, response_type=dict)
  File "/iceberg/backend/utils/request.py", line 119, in get
    return _make_request(
  File "/iceberg/backend/utils/request.py", line 102, in _make_request
    return ResponseObject(response, response_type)
  File "/iceberg/backend/utils/request.py", line 33, in __init__
    self.data = self.handle_response(response)
  File "/iceberg/backend/utils/request.py", line 44, in handle_response
    raise RequestException(f"Client error with status {self.status_code}", response=response)
requests.exceptions.RequestException: Client error with status 401
2024-06-15 13:19:25 | ❌ ERROR     | realdebrid.is_cached - Error checking cache for streams
Traceback (most recent call last):
  File "/iceberg/backend/program/downloaders/realdebrid.py", line 123, in is_cached
    response = get(f"{RD_BASE_URL}/torrents/instantAvailability/{streams}/", additional_headers=self.auth_headers, response_type=dict)
  File "/iceberg/backend/utils/request.py", line 119, in get
    return _make_request(
  File "/iceberg/backend/utils/request.py", line 102, in _make_request
    return ResponseObject(response, response_type)
  File "/iceberg/backend/utils/request.py", line 33, in __init__
    self.data = self.handle_response(response)
  File "/iceberg/backend/utils/request.py", line 44, in handle_response
    raise RequestException(f"Client error with status {self.status_code}", response=response)
requests.exceptions.RequestException: Client error with status 401
2024-06-15 13:19:26 | ❌ ERROR     | realdebrid.is_cached - Error checking cache for streams
Traceback (most recent call last):
  File "/iceberg/backend/program/downloaders/realdebrid.py", line 123, in is_cached
    response = get(f"{RD_BASE_URL}/torrents/instantAvailability/{streams}/", additional_headers=self.auth_headers, response_type=dict)
  File "/iceberg/backend/utils/request.py", line 119, in get
    return _make_request(
  File "/iceberg/backend/utils/request.py", line 102, in _make_request
    return ResponseObject(response, response_type)
  File "/iceberg/backend/utils/request.py", line 33, in __init__
    self.data = self.handle_response(response)
  File "/iceberg/backend/utils/request.py", line 44, in handle_response
    raise RequestException(f"Client error with status {self.status_code}", response=response)
requests.exceptions.RequestException: Client error with status 401
2024-06-15 13:19:27 | ❌ ERROR     | realdebrid.is_cached - Error checking cache for streams
Traceback (most recent call last):
  File "/iceberg/backend/program/downloaders/realdebrid.py", line 123, in is_cached
    response = get(f"{RD_BASE_URL}/torrents/instantAvailability/{streams}/", additional_headers=self.auth_headers, response_type=dict)
  File "/iceberg/backend/utils/request.py", line 119, in get
    return _make_request(
  File "/iceberg/backend/utils/request.py", line 102, in _make_request
    return ResponseObject(response, response_type)
  File "/iceberg/backend/utils/request.py", line 33, in __init__
    self.data = self.handle_response(response)
  File "/iceberg/backend/utils/request.py", line 44, in handle_response
    raise RequestException(f"Client error with status {self.status_code}", response=response)
requests.exceptions.RequestException: Client error with status 401
2024-06-15 13:19:28 | ❌ ERROR     | realdebrid.is_cached - Error checking cache for streams
Traceback (most recent call last):
  File "/iceberg/backend/program/downloaders/realdebrid.py", line 123, in is_cached
    response = get(f"{RD_BASE_URL}/torrents/instantAvailability/{streams}/", additional_headers=self.auth_headers, response_type=dict)
  File "/iceberg/backend/utils/request.py", line 119, in get
    return _make_request(
  File "/iceberg/backend/utils/request.py", line 102, in _make_request
    return ResponseObject(response, response_type)
  File "/iceberg/backend/utils/request.py", line 33, in __init__
    self.data = self.handle_response(response)
  File "/iceberg/backend/utils/request.py", line 44, in handle_response
    raise RequestException(f"Client error with status {self.status_code}", response=response)
requests.exceptions.RequestException: Client error with status 401
2024-06-15 13:19:28 | 🤷‍ NOT_FOUND | realdebrid.is_cached - No wanted cached streams found for The Fall Guy out of 35
```

**Comment by AyushSehrawat** [comment]
@Gaisberg Look into this

**Comment by Gaisberg** [comment]
Torbox isnt fully supported, are you using the torbox branch?

**Comment by subexx** [comment]
Yes. I just wanted to give it a try. guess i will have to stick with real debrid for now.

**Comment by Gaisberg** [comment]
Will be fixed in latest release
