### ISSUE TITLE
program.initialize_services - No Requesting service initialized, you must select at least one.

### ISSUE THREAD

**Issue by qy2009** [rivenmedia/riven#489]
Hi,

I have finished all the 4 steps, and I am using plex watchlist RSS. I manually checked, and that link is working. however, I cannot get it running, from the log, it said program.initialize_services - No Requesting service initialized, you must select at least one.

![image](https://github.com/rivenmedia/riven/assets/51539377/2d45a99f-58ca-461f-8c39-7043db03b3db)

thanks!

**Comment by dreulavelle** [comment]
Your on an old version first of all, and secondly, I need to see logs to be able to help!

**Comment by qy2009** [comment]
you are right. sorry I was on and old image! just updated. however, I still got some issues:

looks like I have plex connection issue and the plex RSS issue? my plex service is red.

TypeError: Cannot read properties of null (reading 'data')
    at mediaServerSettingsToPass (file:///riven/frontend/build/server/chunks/superValidate-BaqJh34q.js:4012:27)
    at load (file:///riven/frontend/build/server/chunks/14-DwEIyfI9.js:26:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async load_server_data (file:///riven/frontend/build/server/index.js:954:18)
    at async Promise.all (index 2)
    at async render_data (file:///riven/frontend/build/server/index.js:2204:19)
    at async resolve2 (file:///riven/frontend/build/server/index.js:3450:22)
    at async respond (file:///riven/frontend/build/server/index.js:3355:22)
    at async Array.ssr (file:///riven/frontend/build/handler.js:1261:3)
24-07-04 05:15:46 | 👾 API       | main.dispatch - GET /services - 200 - 0.00s
24-07-04 05:15:46 | 👾 API       | main.dispatch - GET /settings/get/content - 200 - 0.00s
24-07-04 05:15:46 | 👾 API       | main.dispatch - GET /services - 200 - 0.00s
24-07-04 05:15:46 | 👾 API       | main.dispatch - GET /settings/get/plex - 200 - 0.00s
TypeError: Cannot read properties of null (reading 'data')
    at mediaServerSettingsToPass (file:///riven/frontend/build/server/chunks/superValidate-BaqJh34q.js:4012:27)
    at load (file:///riven/frontend/build/server/chunks/14-DwEIyfI9.js:26:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async load_server_data (file:///riven/frontend/build/server/index.js:954:18)
    at async Promise.all (index 2)
    at async render_data (file:///riven/frontend/build/server/index.js:2204:19)
    at async resolve2 (file:///riven/frontend/build/server/index.js:3450:22)
    at async respond (file:///riven/frontend/build/server/index.js:3355:22)
    at async Array.ssr (file:///riven/frontend/build/handler.js:1261:3)
24-07-04 05:15:50 | 👾 API       | main.dispatch - GET /services - 200 - 0.00s
24-07-04 05:15:50 | 👾 API       | main.dispatch - GET /settings/get/content - 200 - 0.00s
24-07-04 05:15:51 | 👾 API       | main.dispatch - GET /services - 200 - 0.00s
24-07-04 05:15:51 | 👾 API       | main.dispatch - GET /settings/get/scraping - 200 - 0.00s
24-07-04 05:15:52 | 👾 API       | main.dispatch - GET /services - 200 - 0.00s
24-07-04 05:15:52 | 👾 API       | main.dispatch - GET /settings/get/debug,log,symlink,downloaders - 200 - 0.00s
24-07-04 05:15:53 | 👾 API       | main.dispatch - GET /services - 200 - 0.00s
24-07-04 05:15:53 | 👾 API       | main.dispatch - GET /settings/get/version - 200 - 0.00s
24-07-04 05:15:53 | 👾 API       | main.dispatch - GET /services - 200 - 0.00s
24-07-04 05:15:54 | 🤖 DEBUG     | symlink.search_file - Searching for file CSI.Vegas.S02E13.1080p.WEBRip.x265[eztv.re].mp4 in /mnt
24-07-04 05:15:54 | 🔗 SYMLINKER | symlink.wait_for_file - File found for CSI: Vegas S02E13 after searching
24-07-04 05:15:54 | 🤖 DEBUG     | symlink.should_submit - File not found for CSI: Vegas S02E14 at the moment, waiting for it to become available
24-07-04 05:15:54 | ❌ ERROR     | plex_watchlist._get_items_from_rss - An unexpected error occurred while fetching Plex RSS feed from https://rss.plex.tv/xxx: 'types.SimpleNamespace' object has no attribute 'channel'
24-07-04 05:15:54 | ✨ NEW       | program._push_event_queue - Added tt12887536 to the queue
24-07-04 05:15:54 | ✨ NEW       | program._push_event_queue - Added tt3526078 to the queue
24-07-04 05:15:54 | ✨ NEW       | program._push_event_queue - Added tt11188682 to the queue
24-07-04 05:15:54 | ✨ NEW       | program._push_event_queue - Added tt11273352 to the queue
24-07-04 05:15:55 | 👾 API       | main.dispatch - GET /torbox - 200 - 2.63s

**Comment by dreulavelle** [comment]
Front end is broken, so I would edit settings through the settings.json file.  Also there's a bug with Plex Watchlist RSS. Plex changed the response to the endpoint for it so we need to change and adapt to it. You can use Plex Watchlist by itself, just don't use the RSS url part

**Comment by qy2009** [comment]
cool. thanks so much :)
