### ISSUE TITLE
Add opensubtitles credentials to settings.json

### ISSUE THREAD

**Issue by hjongedijk** [rivenmedia/riven#611]
Add the option to add (username, password, API token) to settings.json for opensubtitles so people who have VIP/non-VIP can download it from there own user account

```
ERROR:subliminal.utils:Unexpected error. Discarding provider opensubtitlescom
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/subliminal/core.py", line 192, in download_subtitle
    self[subtitle.provider_name].download_subtitle(subtitle)
  File "/app/.venv/lib/python3.11/site-packages/subliminal/providers/opensubtitlescom.py", line 348, in wrapper
    raise AuthenticationError(msg)
subliminal.exceptions.AuthenticationError: Cannot authenticate with username and password
ERROR:subliminal.core:Invalid subtitle
WARNING:subliminal.core:Provider 'opensubtitlescom' is discarded
WARNING:subliminal.core:Provider 'opensubtitlescom' is discarded
WARNING:subliminal.core:Provider 'opensubtitlescom' is discarded
```

**Comment by dreulavelle** [comment]
```
24-08-12 05:13:22 | ❌ ERROR     | program._process_future_item - Service PostProcessing failed with exception Traceback (most recent call last):
  File "/riven/src/program/program.py", line 333, in _process_future_item
    for i in future.result():
  File "/riven/src/program/db/db_functions.py", line 117, in _run_thread_with_db_item
    for res in fn(input_item):
  File "/riven/src/program/post_processing/__init__.py", line 23, in run
    self.services[Subliminal].run(item)
  File "/riven/src/program/post_processing/subliminal.py", line 56, in run
    subtitles = self.get_subtitles(item)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/riven/src/program/post_processing/subliminal.py", line 39, in get_subtitles
    video = Video.fromname(real_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/subliminal/video.py", line 247, in fromname
    return cls.fromguess(name, guessit(name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/subliminal/video.py", line 232, in fromguess
    return Episode.fromguess(name, guess)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/subliminal/video.py", line 357, in fromguess
    raise ValueError(msg)
ValueError: Insufficient data to process the guess

Traceback (most recent call last):
  File "/riven/src/program/program.py", line 333, in _process_future_item
    for i in future.result():
  File "/riven/src/program/db/db_functions.py", line 117, in _run_thread_with_db_item
    for res in fn(input_item):
  File "/riven/src/program/post_processing/__init__.py", line 23, in run
    self.services[Subliminal].run(item)
  File "/riven/src/program/post_processing/subliminal.py", line 56, in run
    subtitles = self.get_subtitles(item)
  File "/riven/src/program/post_processing/subliminal.py", line 39, in get_subtitles
    video = Video.fromname(real_name)
  File "/app/.venv/lib/python3.11/site-packages/subliminal/video.py", line 247, in fromname
    return cls.fromguess(name, guessit(name))
  File "/app/.venv/lib/python3.11/site-packages/subliminal/video.py", line 232, in fromguess
    return Episode.fromguess(name, guess)
  File "/app/.venv/lib/python3.11/site-packages/subliminal/video.py", line 357, in fromguess
    raise ValueError(msg)
ValueError: Insufficient data to process the guess
```

Another issue with subs. @Gaisberg

**Comment by davidemarcoli** [comment]
@dreulavelle That looks to me like an issue with the parsing library guessit.
