### ISSUE TITLE
500 error when attempting to open Media Server page in settings

### ISSUE THREAD

**Issue by ClarkFamily** [rivenmedia/riven#676]
I'm posting this in the riven repo instead of riven-frontend because it appears to me to be tied to riven's settings.yml. 

I'm running in docker and getting a 500 error when I attempt to access the Media Server settings page. It doesn't matter if I start with clean data folders (for riven and riven-db) and go through the onboarding or provide environment variables that include the Plex specific settings:
RIVEN_UPDATERS_PLEX_ENABLED=true
RIVEN_UPDATERS_PLEX_URL=http://plex:32400
RIVEN_UPDATERS_PLEX_TOKEN=abcdefg # redacted

Settings page error:

![Screenshot 2024-08-30 175429](https://github.com/user-attachments/assets/56f39732-6470-4379-a580-d4f8defcd8a2)

riven-frontend log:

```
TypeError: Cannot read properties of undefined (reading 'enabled')
    at mediaServerSettingsToPass (file:///riven/build/server/chunks/superValidate-D4LVS7OQ.js:3938:45)
    at load (file:///riven/build/server/chunks/21-B7TiyMXQ.js:29:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async load_server_data (file:///riven/build/server/index.js:948:18)
    at async Promise.all (index 2)
    at async render_data (file:///riven/build/server/index.js:2198:19)
    at async resolve2 (file:///riven/build/server/index.js:3448:22)
    at async respond (file:///riven/build/server/index.js:3353:22)
    at async Array.ssr (file:///riven/build/handler.js:1261:3)
```

riven settings.yml updater section:
```
    "updaters": {
        "updater_interval": 120,
        "plex": {
            "enabled": true,
            "token": abcdefg",
            "url": "http://pinky:32400/web"
        }
    },
```

docker images are both latest (08/30/24):
```
  riven-frontend:
    image: spoked/riven-frontend:latest
...    
  riven:
    image: spoked/riven:latest
...
```

**Comment by drondeseries** [comment]
They are aware of it, frontend just have to be updated

**Comment by ClarkFamily** [comment]
Gotcha. Appreciate the response.
