### ISSUE TITLE
Docker container v0.12.3 not starting

### ISSUE THREAD

**Issue by kubo6472** [rivenmedia/riven#705]
Riven is not starting on the :latest tag (v0.12.3 as of 11:27 UTC 21.9.2024)

Error is as follows:
```sh
riven  | Starting Container with 1000:1000 permissions...
riven  | adduser: : No such file or directory
riven  | Container Initialization complete.
riven  | Starting Riven (Backend)...
riven  | Traceback (most recent call last):
riven  |   File "/riven/src/main.py", line 14, in <module>
riven  |     from controllers.default import router as default_router
riven  |   File "/riven/src/controllers/default.py", line 6, in <module>
riven  |     from program.content.trakt import TraktContent
riven  |   File "/riven/src/program/__init__.py", line 3, in <module>
riven  |     from program.media.item import MediaItem  # noqa: F401
riven  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
riven  |   File "/riven/src/program/media/__init__.py", line 1, in <module>
riven  |     from .item import Episode, MediaItem, Movie, Season, Show  # noqa
riven  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
riven  |   File "/riven/src/program/media/item.py", line 13, in <module>
riven  |     from program.db.db import db
riven  |   File "/riven/src/program/db/db.py", line 9, in <module>
riven  |     from program.settings.manager import settings_manager
riven  |   File "/riven/src/program/settings/manager.py", line 106, in <module>
riven  |     settings_manager = SettingsManager()
riven  |                        ^^^^^^^^^^^^^^^^^
riven  |   File "/riven/src/program/settings/manager.py", line 28, in __init__
riven  |     validate(instance=settings_dict, schema=self.schema)
riven  |   File "/app/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 1326, in validate
riven  |     cls = validator_for(schema)
riven  |           ^^^^^^^^^^^^^^^^^^^^^
riven  |   File "/app/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 1398, in validator_for
riven  |     if schema is True or schema is False or "$schema" not in schema:
riven  |                                             ^^^^^^^^^^^^^^^^^^^^^^^
riven  | TypeError: argument of type 'NoneType' is not iterable
riven exited with code 0

```

The old riven [v0.11.1](https://hub.docker.com/layers/spoked/riven/v0.11.1/images/sha256-dd39c8c9ef2c43daf5f73607776b1c5f2e405610f64bc07baaf956aff43b051a?context=explore) works fine.

**Comment by dreulavelle** [comment]
looks like that jsonschema library is shit lol. will fix :)

**Comment by dreulavelle** [comment]
0.12.4 image is building now, it should fix it. :)
