### ISSUE TITLE
Trakt 502 Responses

### ISSUE THREAD

**Issue by subvhome** [rivenmedia/riven#767]
I pull from Gary's latest releases and everything has been working well. Now I receive an error which claims the link is pulling from page 18.. however visiting the list shows 2 pages.. which is odd. Maybe he cleaned the list or a site error .. in any event here is the error

24-10-04 08:03:20 | ðŸž DEBUG     | event_manager._find_or_create_executor - Executor for TraktContent found.
Request failed: HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries
exceeded with url: /users/garycrawfordgc/lists/latest-releases/items?page=18 (Caused by ResponseError('too many 502 error responses'))
urllib3.exceptions.ResponseError: too many 502 error responses
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 944, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 944, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 944, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 934, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /users/garycrawfordgc/lists/latest-releases/items?page=18 (Caused by ResponseError('too many 502 error responses'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/riven/src/utils/request.py", line 106, in _make_request
    response = session.request(
               ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/requests/adapters.py", line 691, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /users/garycrawfordgc/lists/latest-releases/items?page=18 (Caused by ResponseError('too many 502 error responses'))
Request failed
urllib3.exceptions.ResponseError: too many 502 error responses
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 944, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 944, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 944, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 934, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /users/garycrawfordgc/lists/latest-releases/items?page=18 (Caused by ResponseError('too many 502 error responses'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/riven/src/utils/request.py", line 106, in _make_request
    response = session.request(
               ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/requests/adapters.py", line 691, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /users/garycrawfordgc/lists/latest-releases/items?page=18 (Caused by ResponseError('too many 502 error responses'))
24-10-04 08:03:26 | âŒ  ERROR     | trakt._fetch_data - Error fetching data: Server error with status 500
24-10-04 08:03:35 | ðŸž DEBUG     | event_manager._process_future - Service TraktContent executed
24-10-04 08:03:42 | ðŸ‘¾ API       | main.dispatch - GET / - 200 - 0.00s
24-10-04 08:03:53 | ðŸž DEBUG     | event_manager._process_future - Service PlexWatchlist executed
24-10-04 08:04:12 | ðŸ‘¾ API       | main.dispatch - GET / - 200 - 0.00s
24-10-04 08:04:20 | ðŸž DEBUG     | event_manager.submit_job - Submitting service PlexWatchlist to be executed
24-10-04 08:04:20 | ðŸž DEBUG     | event_manager._find_or_create_executor - Executor for PlexWatchlist found.

**Comment by subvhome** [comment]
I counted the list. It's length is indeed to pages :). Making sure I wasn't restricted or anything

**Comment by subvhome** [comment]
This could be closed. I did a fresh install and am not using trakt users lists at the moment.
