### ISSUE TITLE
Error occured when removing specific series, in my case its gintama (working on other series).

### ISSUE THREAD

**Issue by xanderford00** [rivenmedia/riven#775]
can't remove gintama once added : 24-10-09 14:13:59 | ❌ ERROR     | event_manager._process_future - Error in future for <Future at 0x7fc6e67d3890 state=finished returned generator>: list.remove(x): x not in list
24-10-09 14:13:59 | ❌ ERROR     | event_manager._process_future - Traceback (most recent call last):
  File "/riven/src/utils/event_manager.py", line 63, in _process_future
    self._futures.remove(future)
ValueError: list.remove(x): x not in list

Traceback (most recent call last):
  File "/riven/src/utils/event_manager.py", line 63, in _process_future
    self._futures.remove(future)
ValueError: list.remove(x): x not in list

**Comment by xanderford00** [comment]
To replicate : Add a series (e.g. gintama) -> let it scrape for a while (in my case its until episode 9-10) , remove it.

**Comment by machetie** [comment]
Consolidating with #874 where we're tracking all media deletion related issues. Please follow that issue for updates.
