### ISSUE TITLE
Downloader Proxy settings

### ISSUE THREAD

**Issue by DamnDam** [rivenmedia/riven#807]
Hello!

Setting a proxy_url seems broken

settings.json:
```
"real_debrid": {
    "enabled": true,
    "api_key": "XXX",
    "proxy_enabled": true,
    "proxy_url": "http://my_http_proxy:8080"
},
```

logs:
```
riven           | 24-10-21 10:16:24 | ❌ ERROR     | realdebrid.validate - Failed to validate Real-Debrid settings: 'str' object has no attribute 'get'
riven           | Traceback (most recent call last):
riven           |   File "/riven/src/program/downloaders/realdebrid.py", line 72, in validate
riven           |     user_info = get("/user")
riven           |   File "/riven/src/program/downloaders/realdebrid.py", line 176, in get
riven           |     return request.get(
riven           |   File "/riven/src/utils/request.py", line 150, in get
riven           |     return _make_request(
riven           |   File "/riven/src/utils/request.py", line 106, in _make_request
riven           |     response = session.request(
riven           |   File "/app/.venv/lib/python3.11/site-packages/requests/sessions.py", line 579, in request
riven           |     settings = self.merge_environment_settings(
riven           |   File "/app/.venv/lib/python3.11/site-packages/requests/sessions.py", line 759, in merge_environment_settings
riven           |     no_proxy = proxies.get("no_proxy") if proxies is not None else None
riven           | AttributeError: 'str' object has no attribute 'get'
riven           | 24-10-21 10:16:24 | ❌ ERROR     | __init__.validate - No downloader service is initialized. Please initialize a downloader service.
riven           | 24-10-21 10:16:24 | ❌ ERROR     | program.initialize_services - No Downloader service initialized, you must enable at least one.
```

Thank you!

**Comment by dreulavelle** [comment]
Is the proxy url even necessary anymore? It was to help with the RD api changes before when they added ratelimiting.. but we fixed that internally and I dont even think this is necessary anymore

**Comment by DamnDam** [comment]
I just like having all my zurg/riven stack behind my VPN.
But it's not urgent

**Comment by dreulavelle** [comment]
You dont need a VPN when working with debrid providers as they handle the connections. Your ISP won't see any of that "torrent" traffic

**Comment by davidemarcoli** [comment]
@DamnDam Please try in the newest version and open a new issue if the problem still exists
